[package]
name = "first-gui"
version = "0.1.0"
authors = ["Shub1427 <shub1493biswas@gmail.com>"]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/maps4print/azul", rev = "a6d58ae4fc8e2657981cc510d9f7fbcdc5af0023" }
